# Generated by Django 3.2.3 on 2021-06-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('mobile', models.CharField(default='', max_length=50)),
                ('dob', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('nationality', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=500)),
                ('languages', models.CharField(default='', max_length=50)),
                ('pic', models.FileField(upload_to='images')),
                ('degreepercentage', models.CharField(default='', max_length=50)),
                ('degreebranch', models.CharField(default='', max_length=50)),
                ('intermediatepercentage', models.CharField(default='', max_length=50)),
                ('intermediatebranch', models.CharField(default='', max_length=50)),
                ('sscpercentage', models.CharField(default='', max_length=50)),
                ('skills', models.CharField(default='', max_length=5000)),
                ('personalstrengths', models.CharField(default='', max_length=5000)),
                ('professionalstrengths', models.CharField(default='', max_length=5000)),
                ('projecttitle', models.CharField(default='', max_length=5000)),
                ('projectdescription', models.CharField(default='', max_length=5000)),
                ('careerobjective', models.CharField(default='', max_length=5000)),
                ('yearofExperience', models.CharField(default='', max_length=50)),
                ('currentworkingcompany', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
